/*
 * Copyright 2018, Socializing Syndicate Corp.
 */
const EMAIL_DOMAIN = 'gmail.com'
const EMAIL_PROVIDER = 'gmail'

//Errors returned by backend
const NOT_VERIFIED = 'NOT_VERIFIED'
const BAD_EMAIL_OR_PASSWORD = 'BAD_EMAIL_OR_PASSWORD'
const INVALID_INPUT = 'INVALID_INPUT'
const ALREADY_EXISTS = 'ALREADY_EXISTS'
const ALREADY_EXISTS_UNVERIFIED = 'ALREADY_EXISTS_UNVERIFIED'
const ALREADY_VERIFIED = 'ALREADY_VERIFIED'
const TOKEN_EXPIRED = 'TOKEN_EXPIRED'
const DATABASE_ERROR = 'DATABASE_ERROR'
const SENDING_MAIL_ERROR = 'SENDING_MAIL_ERROR'

const PASSWORD_REGULAR_EXP = '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$'

module.exports = {
  EMAIL_DOMAIN, EMAIL_PROVIDER, NOT_VERIFIED,
  BAD_EMAIL_OR_PASSWORD, INVALID_INPUT, TOKEN_EXPIRED,
  ALREADY_EXISTS, ALREADY_EXISTS_UNVERIFIED, DATABASE_ERROR,
  SENDING_MAIL_ERROR, PASSWORD_REGULAR_EXP
}
